import { calcMilliseconds } from "./time";
import { languages } from "@codemirror/language-data";

const expirationOptions = [
  { id: 1, name: "Never", value: "never", ms: 0 },
  { id: 2, name: "10 Minutes", value: "10m", ms: 10 * 60 * 1000 },
  { id: 3, name: "1 Hour", value: "1h", ms: 60 * 60 * 1000 },
  { id: 4, name: "1 Day", value: "1D", ms: 24 * 60 * 60 * 1000 },
  { id: 5, name: "1 Week", value: "1W", ms: 7 * 24 * 60 * 60 * 1000 },
  { id: 6, name: "2 Weeks", value: "2W", ms: 14 * 24 * 60 * 60 * 1000 },
  { id: 7, name: "1 Month", value: "1M", ms: calcMilliseconds(1, "M") },
  { id: 8, name: "6 Months", value: "6M", ms: calcMilliseconds(6, "M") },
  { id: 9, name: "1 Year", value: "1Y", ms: calcMilliseconds(1, "Y") },
];

const syntaxOptions = [
  { id: 0, name: "Plaintext", value: "Plaintext" },
  { id: 1, name: "C", value: "C" },
  { id: 2, name: "C++", value: "C++" },
  { id: 3, name: "CQL", value: "CQL" },
  { id: 4, name: "CSS", value: "CSS" },
  { id: 5, name: "HTML", value: "HTML" },
  { id: 6, name: "Java", value: "Java" },
  { id: 7, name: "JavaScript", value: "JavaScript" },
  { id: 8, name: "JSON", value: "JSON" },
  { id: 9, name: "JSX", value: "JSX" },
  { id: 10, name: "MariaDB SQL", value: "MariaDB SQL" },
  { id: 11, name: "Markdown", value: "Markdown" },
  { id: 12, name: "MS SQL", value: "MS SQL" },
  { id: 13, name: "MySQL", value: "MySQL" },
  { id: 14, name: "PHP", value: "PHP" },
  { id: 15, name: "PLSQL", value: "PLSQL" },
  { id: 16, name: "PostgreSQL", value: "PostgreSQL" },
  { id: 17, name: "Python", value: "Python" },
  { id: 18, name: "Rust", value: "Rust" },
  { id: 19, name: "SQL", value: "SQL" },
  { id: 20, name: "SQLite", value: "SQLite" },
  { id: 21, name: "TSX", value: "TSX" },
  { id: 22, name: "TypeScript", value: "TypeScript" },
  { id: 23, name: "WebAssembly", value: "WebAssembly" },
  { id: 24, name: "XML", value: "XML" },
  { id: 25, name: "APL", value: "APL" },
  { id: 26, name: "PGP", value: "PGP" },
  { id: 27, name: "ASN.1", value: "ASN.1" },
  { id: 28, name: "Asterisk", value: "Asterisk" },
  { id: 29, name: "Brainfuck", value: "Brainfuck" },
  { id: 30, name: "Cobol", value: "Cobol" },
  { id: 31, name: "C#", value: "C#" },
  { id: 32, name: "Clojure", value: "Clojure" },
  { id: 33, name: "ClojureScript", value: "ClojureScript" },
  { id: 34, name: "Closure Stylesheets (GSS)", value: "Closure Stylesheets (GSS)" },
  { id: 35, name: "CMake", value: "CMake" },
  { id: 36, name: "CoffeeScript", value: "CoffeeScript" },
  { id: 37, name: "Common Lisp", value: "Common Lisp" },
  { id: 38, name: "Cypher", value: "Cypher" },
  { id: 39, name: "Cython", value: "Cython" },
  { id: 40, name: "Crystal", value: "Crystal" },
  { id: 41, name: "D", value: "D" },
  { id: 42, name: "Dart", value: "Dart" },
  { id: 43, name: "diff", value: "diff" },
  { id: 44, name: "Dockerfile", value: "Dockerfile" },
  { id: 45, name: "DTD", value: "DTD" },
  { id: 46, name: "Dylan", value: "Dylan" },
  { id: 47, name: "EBNF", value: "EBNF" },
  { id: 48, name: "ECL", value: "ECL" },
  { id: 49, name: "edn", value: "edn" },
  { id: 50, name: "Eiffel", value: "Eiffel" },
  { id: 51, name: "Elm", value: "Elm" },
  { id: 52, name: "Erlang", value: "Erlang" },
  { id: 53, name: "Esper", value: "Esper" },
  { id: 54, name: "Factor", value: "Factor" },
  { id: 55, name: "FCL", value: "FCL" },
  { id: 56, name: "Forth", value: "Forth" },
  { id: 57, name: "Fortran", value: "Fortran" },
  { id: 58, name: "F#", value: "F#" },
  { id: 59, name: "Gas", value: "Gas" },
  { id: 60, name: "Gherkin", value: "Gherkin" },
  { id: 61, name: "Go", value: "Go" },
  { id: 62, name: "Groovy", value: "Groovy" },
  { id: 63, name: "Haskell", value: "Haskell" },
  { id: 64, name: "Haxe", value: "Haxe" },
  { id: 65, name: "HXML", value: "HXML" },
  { id: 66, name: "HTTP", value: "HTTP" },
  { id: 67, name: "IDL", value: "IDL" },
  { id: 68, name: "JSON-LD", value: "JSON-LD" },
  { id: 69, name: "Jinja2", value: "Jinja2" },
  { id: 70, name: "Julia", value: "Julia" },
  { id: 71, name: "Kotlin", value: "Kotlin" },
  { id: 72, name: "LESS", value: "LESS" },
  { id: 73, name: "LiveScript", value: "LiveScript" },
  { id: 74, name: "Lua", value: "Lua" },
  { id: 75, name: "mIRC", value: "mIRC" },
  { id: 76, name: "Mathematica", value: "Mathematica" },
  { id: 77, name: "Modelica", value: "Modelica" },
  { id: 78, name: "MUMPS", value: "MUMPS" },
  { id: 79, name: "Mbox", value: "Mbox" },
  { id: 80, name: "Nginx", value: "Nginx" },
  { id: 81, name: "NSIS", value: "NSIS" },
  { id: 82, name: "NTriples", value: "NTriples" },
  { id: 83, name: "Objective-C", value: "Objective-C" },
  { id: 84, name: "Objective-C++", value: "Objective-C++" },
  { id: 85, name: "OCaml", value: "OCaml" },
  { id: 86, name: "Octave", value: "Octave" },
  { id: 87, name: "Oz", value: "Oz" },
  { id: 88, name: "Pascal", value: "Pascal" },
  { id: 89, name: "Perl", value: "Perl" },
  { id: 90, name: "Pig", value: "Pig" },
  { id: 91, name: "PowerShell", value: "PowerShell" },
  { id: 92, name: "Properties files", value: "Properties files" },
  { id: 93, name: "ProtoBuf", value: "ProtoBuf" },
  { id: 94, name: "Puppet", value: "Puppet" },
  { id: 95, name: "Q", value: "Q" },
  { id: 96, name: "R", value: "R" },
  { id: 97, name: "RPM Changes", value: "RPM Changes" },
  { id: 98, name: "RPM Spec", value: "RPM Spec" },
  { id: 99, name: "Ruby", value: "Ruby" },
  { id: 100, name: "SAS", value: "SAS" },
  { id: 101, name: "Sass", value: "Sass" },
  { id: 102, name: "Scala", value: "Scala" },
  { id: 103, name: "Scheme", value: "Scheme" },
  { id: 104, name: "SCSS", value: "SCSS" },
  { id: 105, name: "Shell", value: "Shell" },
  { id: 106, name: "Sieve", value: "Sieve" },
  { id: 107, name: "Smalltalk", value: "Smalltalk" },
  { id: 108, name: "Solr", value: "Solr" },
  { id: 109, name: "SML", value: "SML" },
  { id: 110, name: "SPARQL", value: "SPARQL" },
  { id: 111, name: "Spreadsheet", value: "Spreadsheet" },
  { id: 112, name: "Squirrel", value: "Squirrel" },
  { id: 113, name: "Stylus", value: "Stylus" },
  { id: 114, name: "Swift", value: "Swift" },
  { id: 115, name: "sTeX", value: "sTeX" },
  { id: 116, name: "LaTeX", value: "LaTeX" },
  { id: 117, name: "SystemVerilog", value: "SystemVerilog" },
  { id: 118, name: "Tcl", value: "Tcl" },
  { id: 119, name: "Textile", value: "Textile" },
  { id: 120, name: "TiddlyWiki", value: "TiddlyWiki" },
  { id: 121, name: "Tiki wiki", value: "Tiki wiki" },
  { id: 122, name: "TOML", value: "TOML" },
  { id: 123, name: "Troff", value: "Troff" },
  { id: 124, name: "TTCN", value: "TTCN" },
  { id: 125, name: "TTCN_CFG", value: "TTCN_CFG" },
  { id: 126, name: "Turtle", value: "Turtle" },
  { id: 127, name: "Web IDL", value: "Web IDL" },
  { id: 128, name: "VB.NET", value: "VB.NET" },
  { id: 129, name: "VBScript", value: "VBScript" },
  { id: 130, name: "Velocity", value: "Velocity" },
  { id: 131, name: "Verilog", value: "Verilog" },
  { id: 132, name: "VHDL", value: "VHDL" },
  { id: 133, name: "XQuery", value: "XQuery" },
  { id: 134, name: "Yacas", value: "Yacas" },
  { id: 135, name: "YAML", value: "YAML" },
  { id: 136, name: "Z80", value: "Z80" },
  { id: 137, name: "MscGen", value: "MscGen" },
  { id: 138, name: "Xù", value: "Xù" },
  { id: 139, name: "MsGenny", value: "MsGenny" },
  { id: 140, name: "Vue", value: "Vue" },
  { id: 141, name: "Angular Template", value: "Angular Template" },
];

const getSyntaxLang = async (name: string) => {
  if (name === "Plaintext") {
    return undefined;
  }
  const languageDescription = languages.find((l) => l.name === name);
  return languageDescription?.load();
};

export { expirationOptions, syntaxOptions, getSyntaxLang };
